// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuePriority } from "./IssuePriority";

export type CreateIssuePayload = { title: string, description: string, priority: IssuePriority, project?: string | null, parent?: string | null, assignee?: string | null, };
