// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeKind } from "./EmployeeKind";
import type { EmployeeProviderConfig } from "./EmployeeProviderConfig";
import type { EmployeeRole } from "./EmployeeRole";
import type { EmployeeRuntimeConfig } from "./EmployeeRuntimeConfig";

export type CreateEmployeePayload = { name: string, kind: EmployeeKind, role: EmployeeRole, title: string, icon: string, color: string, capabilities: Array<string>, provider_config: EmployeeProviderConfig | null, runtime_config: EmployeeRuntimeConfig | null, heartbeat_md?: string | null, soul_md?: string | null, agents_md?: string | null, tools_md?: string | null, };
