// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeKind } from './EmployeeKind'
import type { EmployeePermissions } from './EmployeePermissions'
import type { EmployeeProviderConfig } from './EmployeeProviderConfig'
import type { EmployeeRole } from './EmployeeRole'
import type { EmployeeRuntimeConfig } from './EmployeeRuntimeConfig'
import type { EmployeeStatus } from './EmployeeStatus'

export type Employee = {
  id: string
  name: string
  role: EmployeeRole
  kind: EmployeeKind
  icon: string
  color: string
  title: string
  status: EmployeeStatus
  capabilities: Array<string>
  permissions: EmployeePermissions | null
  reports_to: string | null
  provider_config: EmployeeProviderConfig | null
  runtime_config: EmployeeRuntimeConfig | null
  chain_of_command: Array<Employee>
  created_at: string
}
