// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeLifeTreeNode } from './EmployeeLifeTreeNode'

export type EmployeeLifeTreeResult = { root_path: string; nodes: Array<EmployeeLifeTreeNode> }
