// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmployeeRuntimeConfig = { heartbeat_interval_sec: bigint, heartbeat_prompt: string, wake_on_demand: boolean, max_concurrent_runs: bigint, };
