// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeLifeFileKind } from './EmployeeLifeFileKind'

export type EmployeeLifeFileResult = { path: string; content: string; kind: EmployeeLifeFileKind; editable: boolean }
