// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Employee } from './Employee'
import type { EmployeeStreamSnapshotDto } from './EmployeeStreamSnapshotDto'

export type EmployeeStreamMessageDto =
  | { type: 'snapshot'; snapshot: EmployeeStreamSnapshotDto }
  | { type: 'upsert'; employee: Employee }
  | { type: 'delete'; employee_id: string }
