// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportEmployeePayload = { base_url: string | null, slug: string, force: boolean, skip_duplicate_skills: boolean, force_skills: boolean, };
