// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueStatus } from "./IssueStatus";

export type IssueActionKind = "create" | "add_comment" | "add_attachment" | "check_out" | "release" | "unassign" | { "assign": { employee: string, } } | { "status_change": { from: IssueStatus, to: IssueStatus, } } | "update";
