// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueEventKindDto =
  | "created"
  | "updated"
  | "comment_added"
  | "attachment_added"
  | "assigned"
  | "unassigned"
  | "checked_out"
  | "released";
