// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IssueStatus = "Backlog" | "Todo" | "InProgress" | "InReview" | "Blocked" | "Done" | "Cancelled" | "Archived";
