// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueStatus } from "./IssueStatus";

export type IssueActionKind = "Create" | "AddComment" | "AddAttachment" | "CheckOut" | "Release" | "Unassign" | { "Assign": { employee: string, } } | { "StatusChange": { from: IssueStatus, to: IssueStatus, } } | "Update";
