// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuePriority } from "./IssuePriority";
import type { IssueStatus } from "./IssueStatus";

export type IssuePatch = { title: string | null, description: string | null, status: IssueStatus | null, project: string | null | null, parent: string | null | null, creator: string | null | null, assignee: string | null | null, blocked_by: string | null | null, priority: IssuePriority | null, updated_at: string | null, };
