// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueCommentMentionDto } from "./IssueCommentMentionDto";

export type IssueCommentDto = { id: string, comment: string, mentions: Array<IssueCommentMentionDto>, creator: string, run_id: string | null, created_at: string, };
