// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuePriority } from "./IssuePriority";
import type { IssueStatus } from "./IssueStatus";

export type IssuePatch = { title?: string, description?: string, status?: IssueStatus, project?: string | null, parent?: string | null, creator?: string | null, assignee?: string | null, blocked_by?: string | null, priority?: IssuePriority, updated_at?: string, };
