// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueAttachmentKind } from "./IssueAttachmentKind";

export type IssueAttachment = { name: string, attachment_kind: IssueAttachmentKind, attachment: string, mime_kind: string, size: number, };
