// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueAttachmentKind } from "./IssueAttachmentKind";

export type IssueAttachmentDto = { id: string, name: string, attachment_kind: IssueAttachmentKind, mime_kind: string, size: bigint, run_id: string | null, created_at: string, };
