// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueAttachment } from "./IssueAttachment";

export type IssueAttachmentDto = { id: string, attachment: IssueAttachment, creator: string, run_id: string | null, created_at: string, };
