// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectDto = { id: string, description: string, name: string, working_directories: Array<string>, created_at: string, updated_at: string, };
