// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";
import type { RunTrigger } from "./RunTrigger";
import type { UsageMetrics } from "./UsageMetrics";

export type RunSummaryDto = { id: string, employee_id: string, status: RunStatus, trigger: RunTrigger, usage: UsageMetrics | null, created_at: string, started_at: string | null, completed_at: string | null, };
