// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramLinkStatus } from "./TelegramLinkStatus";
import type { TelegramNotificationPreferences } from "./TelegramNotificationPreferences";

export type TelegramLinkDto = { id: string, employee_id: string, telegram_user_id: bigint, telegram_chat_id: bigint, status: TelegramLinkStatus, notification_preferences: TelegramNotificationPreferences, created_at: string, updated_at: string, last_seen_at: string | null, };
