// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolId } from "./ToolId";
import type { ToolUseResponseData } from "./ToolUseResponseData";

export type ToolUseResponseSuccess = { success: boolean, tool_id: ToolId, data: ToolUseResponseData, };
