// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { RunTrigger } from "./RunTrigger";

export type TriggerRunPayload = { employee_id: string, trigger: RunTrigger | null, prompt: string | null, reasoning_effort: ReasoningEffort | null, };
