// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "./ReasoningEffort";
import type { TurnStep } from "./TurnStep";

export type TurnDto = { id: string, steps: Array<TurnStep>, run_id: string, reasoning_effort: ReasoningEffort | null, created_at: string, };
