// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStepContents } from "./TurnStepContents";
import type { TurnStepStatus } from "./TurnStepStatus";

export type TurnStep = { contents: TurnStepContents, status: TurnStepStatus, created_at: string, completed_at: string | null, };
