// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentsVisibility } from "./ContentsVisibility";

export type TurnStepImage = { blob: string, media_kind: string, visibility: ContentsVisibility, };
