// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MentionPayload } from "./MentionPayload";

export type AddCommentPayload = { comment: string, reopen_issue: boolean | null, mentions: Array<MentionPayload>, };
