// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueLabel } from "./IssueLabel";
import type { IssuePriority } from "./IssuePriority";
import type { IssueStatus } from "./IssueStatus";

export type CreateIssuePayload = { title: string, description: string, labels?: Array<IssueLabel> | null, status: IssueStatus, priority: IssuePriority, project?: string | null, parent?: string | null, assignee?: string | null, };
