// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramLinkCodeDto } from "./TelegramLinkCodeDto";

export type CreateTelegramLinkCodeResponse = { code: string, record: TelegramLinkCodeDto, };
