// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProjectPayload = { description: string, dreaming_enabled: boolean | null, name: string, working_directories: Array<string>, };
