// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeLifeFileKind } from "./EmployeeLifeFileKind";

export type EmployeeLifeTreeNode = { "type": "directory", name: string, path: string, children: Array<EmployeeLifeTreeNode>, } | { "type": "file", name: string, path: string, kind: EmployeeLifeFileKind, editable: boolean, };
