// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerAuthState } from "./McpServerAuthState";

export type EnableMcpServerPayload = { server_id: string, display_name: string, description: string, auth_state: McpServerAuthState, };
