// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileReadPayload } from "./FileReadPayload";
import type { FilesReadErrorPayload } from "./FilesReadErrorPayload";

export type FilesReadPayload = { files: Array<FileReadPayload>, errors?: Array<FilesReadErrorPayload>, };
