// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueActionKind } from "./IssueActionKind";

export type IssueActionDto = { id: string, action_kind: IssueActionKind, creator: string, run_id: string | null, created_at: string, };
