// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueDto } from "./IssueDto";
import type { IssueEventKindDto } from "./IssueEventKindDto";
import type { IssueStreamSnapshotDto } from "./IssueStreamSnapshotDto";

export type IssueStreamMessageDto = { "type": "snapshot", snapshot: IssueStreamSnapshotDto, } | { "type": "upsert", kind: IssueEventKindDto, issue: IssueDto, };
