// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpOauthMetadataDto } from "./McpOauthMetadataDto";
import type { McpServerAuthState } from "./McpServerAuthState";

export type McpOauthLaunchDto = { server_id: string, authorization_url: string, redirect_uri: string, auth_state: McpServerAuthState, auth_summary: string | null, suggested_scopes: Array<string>, metadata: McpOauthMetadataDto | null, };
