// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpOauthMetadataDto = { authorization_endpoint: string, token_endpoint: string, registration_endpoint: string | null, issuer: string | null, scopes_supported: Array<string>, };
