// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerAuthState } from "./McpServerAuthState";

export type McpServerPatch = { display_name?: string, description?: string, transport?: string, endpoint_url?: string, auth_state?: McpServerAuthState, auth_summary?: string | null, enabled?: boolean, };
