// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MinionPatch = { slug?: string, display_name?: string, description?: string, enabled?: boolean, prompt?: string | null, };
