// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MinionPatchPayload = { slug: string | null, display_name: string | null, description: string | null, enabled: boolean | null, prompt: string | null | null, };
