// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MinionSource } from "./MinionSource";

export type MinionDto = { id: string, source: MinionSource, slug: string, display_name: string, description: string, enabled: boolean, prompt: string | null, can_edit_definition: boolean, can_toggle_enabled: boolean, created_at: string, updated_at: string, };
