// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmployeeRole } from "./EmployeeRole";
import type { EmployeeStatus } from "./EmployeeStatus";

export type OrgChart = { id: string, name: string, role: EmployeeRole, title: string, status: EmployeeStatus, capabilities: Array<string>, reports: Array<OrgChart>, };
