// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectPlanListItem } from "./ProjectPlanListItem";

export type ProjectPlansListResult = { plans: Array<ProjectPlanListItem>, };
