// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectPatch = { description?: string, name?: string, working_directories?: Array<string>, updated_at?: string, };
