// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Provider = "anthropic" | "openai" | "open_router" | "mock" | "claude_code" | "codex";
