// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicRunTrigger = "manual" | "conversation" | "timer" | { "issue_assignment": { issue_id: string, } } | { "issue_mention": { issue_id: string, comment_id: string, } };
