// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicRunTrigger } from "./PublicRunTrigger";
import type { RunEnabledMcpServerDto } from "./RunEnabledMcpServerDto";
import type { RunStatus } from "./RunStatus";
import type { TurnDto } from "./TurnDto";
import type { UsageMetrics } from "./UsageMetrics";

export type RunDto = { id: string, employee_id: string, status: RunStatus, trigger: PublicRunTrigger, enabled_mcp_servers: Array<RunEnabledMcpServerDto>, usage: UsageMetrics | null, created_at: string, turns: Array<TurnDto>, started_at: string | null, completed_at: string | null, };
