// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunDto } from "./RunDto";
import type { RunStreamSnapshotDto } from "./RunStreamSnapshotDto";
import type { RunSummaryDto } from "./RunSummaryDto";

export type RunStreamMessageDto = { "type": "snapshot", snapshot: RunStreamSnapshotDto, } | { "type": "summary_upsert", run: RunSummaryDto, } | { "type": "detail_upsert", run: RunDto, };
