// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunStatus } from "./RunStatus";

export type RunsPageQuery = { employee: string | null, status: RunStatus | null, page: number | null, per_page: number | null, };
