// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunSummaryDto } from "./RunSummaryDto";

export type RunSummaryPageDto = { items: Array<RunSummaryDto>, page: number, per_page: number, total: bigint, total_pages: number, };
