// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunDto } from "./RunDto";
import type { RunSummaryDto } from "./RunSummaryDto";

export type RunStreamSnapshotDto = { recent_runs: Array<RunSummaryDto>, running_runs: Array<RunSummaryDto>, running_run_details: Array<RunDto>, };
