// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramParseMode } from "./TelegramParseMode";

export type TelegramConfigPatch = { bot_username: string | null | null, parse_mode: TelegramParseMode | null | null, enabled: boolean | null, updated_at: string | null, };
