// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramCorrelationKind } from "./TelegramCorrelationKind";
import type { TelegramMessageDirection } from "./TelegramMessageDirection";

export type TelegramMessageCorrelationDto = { id: string, telegram_chat_id: bigint, telegram_message_id: bigint, direction: TelegramMessageDirection, kind: TelegramCorrelationKind, issue_id: string | null, run_id: string | null, employee_id: string | null, text_preview: string | null, created_at: string, updated_at: string, };
