// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TelegramLinkCodeDto = { id: string, employee_id: string, code_last4: string, expires_at: string, claimed_at: string | null, claimed_chat_id: bigint | null, claimed_user_id: bigint | null, created_at: string, };
