// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalSnapshot } from "./TerminalSnapshot";

export type TerminalPayload = { terminal_id: string, 
/**
 * Present for snapshot responses.
 */
snapshot: TerminalSnapshot | null, };
