// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolUseResponseError } from "./ToolUseResponseError";
import type { ToolUseResponseSuccess } from "./ToolUseResponseSuccess";

export type ToolUseResponse = { "type": "success" } & ToolUseResponseSuccess | { "type": "error" } & ToolUseResponseError;
