// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolId = "files_read" | "apply_patch" | "shell" | "enable_mcp_server" | { "mcp": string } | { "unknown": string };
