// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PublicRunTrigger } from "./PublicRunTrigger";
import type { ReasoningEffort } from "./ReasoningEffort";

export type TriggerRunPayload = { employee_id: string, trigger: PublicRunTrigger | null, prompt: string | null, reasoning_effort: ReasoningEffort | null, };
