// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentsVisibility } from "./ContentsVisibility";

export type TurnStepThinking = { thinking: string, signature: string, visibility: ContentsVisibility, };
