// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStepImage } from "./TurnStepImage";
import type { TurnStepText } from "./TurnStepText";
import type { TurnStepThinking } from "./TurnStepThinking";
import type { TurnStepToolResult } from "./TurnStepToolResult";
import type { TurnStepToolUse } from "./TurnStepToolUse";

export type TurnStepContent = { "Text": TurnStepText } | { "Image64": TurnStepImage } | { "Thinking": TurnStepThinking } | { "ToolUse": TurnStepToolUse } | { "ToolResult": TurnStepToolResult };
