// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentsVisibility } from "./ContentsVisibility";
import type { ToolId } from "./ToolId";
import type { JsonValue } from "./serde_json/JsonValue";

export type TurnStepToolUse = { tool_use_id: string, tool_id: ToolId, input: JsonValue, visibility: ContentsVisibility, };
