// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentsVisibility } from "./ContentsVisibility";

export type TurnStepText = { text: string, signature: string | null, visibility: ContentsVisibility, };
