// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStepContent } from "./TurnStepContent";
import type { TurnStepRole } from "./TurnStepRole";

export type TurnStepContents = { contents: Array<TurnStepContent>, role: TurnStepRole, };
