// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnStepContents } from "./TurnStepContents";
import type { TurnStepStatus } from "./TurnStepStatus";
import type { UsageMetrics } from "./UsageMetrics";

export type TurnStep = { request: TurnStepContents, response: TurnStepContents, status: TurnStepStatus, usage: UsageMetrics, created_at: string, completed_at: string | null, };
