// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type UpdateProviderPayload = { provider: Provider, api_key: string | null, base_url: string | null, };
