// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramDeliveryMode } from "./TelegramDeliveryMode";
import type { TelegramParseMode } from "./TelegramParseMode";

export type UpsertTelegramConfigPayload = { bot_token: string, webhook_secret: string, bot_username: string | null, webhook_url: string | null, delivery_mode: TelegramDeliveryMode, parse_mode: TelegramParseMode | null, enabled: boolean, };
