// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type UsageMetrics = { provider: Provider | null, model: string | null, input_tokens: bigint | null, output_tokens: bigint | null, total_tokens: bigint | null, estimated_cost_usd: number | null, has_unavailable_token_data: boolean, has_unavailable_cost_data: boolean, };
