// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpOauthMetadataDto } from "./McpOauthMetadataDto";
import type { McpServerAuthState } from "./McpServerAuthState";

export type McpOauthStatusDto = { server_id: string, auth_state: McpServerAuthState, auth_summary: string | null, authorization_url: string | null, has_token: boolean, token_expires_at: bigint | null, scopes: Array<string>, metadata: McpOauthMetadataDto | null, };
