// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpServerAuthState = "not_connected" | "auth_required" | "connected" | "reconnect_required";
