// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerAuthState } from "./McpServerAuthState";

export type McpServerPatchPayload = { display_name: string | null, description: string | null, transport: string | null, endpoint_url: string | null, auth_state: McpServerAuthState | null, auth_summary: string | null | null, enabled: boolean | null, };
