// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssuePriority } from "./IssuePriority";
import type { IssueStatus } from "./IssueStatus";
import type { MyWorkReasonDto } from "./MyWorkReasonDto";

export type MyWorkItemDto = { issue_id: string, issue_identifier: string, title: string, project_id: string | null, project_name: string | null, status: IssueStatus, priority: IssuePriority, reason: MyWorkReasonDto, relevant_at: string, comment_id: string | null, comment_snippet: string | null, };
