// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MyWorkItemDto } from "./MyWorkItemDto";

export type MyWorkResponseDto = { assigned: Array<MyWorkItemDto>, mentioned: Array<MyWorkItemDto>, };
