// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectPatchPayload = { description: string | null, name: string | null, working_directories: Array<string> | null, };
