// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramParseMode } from "./TelegramParseMode";

export type TelegramConfigDto = { id: string, bot_username: string | null, parse_mode: TelegramParseMode | null, enabled: boolean, created_at: string, updated_at: string, };
