// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentsVisibility } from "./ContentsVisibility";
import type { ToolId } from "./ToolId";
import type { ToolUseResponse } from "./ToolUseResponse";

export type TurnStepToolResult = { tool_use_id: string, tool_id: ToolId, content: ToolUseResponse, visibility: ContentsVisibility, };
