// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TelegramParseMode } from "./TelegramParseMode";

export type UpsertTelegramConfigPayload = { bot_token: string, bot_username: string | null, parse_mode: TelegramParseMode | null, enabled: boolean, };
