
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async frontendReady() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("frontend_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDevtools() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_devtools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reloadWindow() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBuildHash() : Promise<Result<string, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_build_hash") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryCreate(request: MemoryCreateRequest) : Promise<Result<MemoryWriteResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_create", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryList(request: MemoryListRequest) : Promise<Result<MemoryListResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_list", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryRead(request: MemoryReadRequest) : Promise<Result<MemoryReadResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_read", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memorySearch(request: MemorySearchCommandRequest) : Promise<Result<MemorySearchResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_search", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryUpdate(request: MemoryUpdateRequest) : Promise<Result<MemoryReadResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_update", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async memoryDelete(request: MemoryDeleteRequest) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("memory_delete", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerList() : Promise<Result<McpServerConfig[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerGet(serverId: string) : Promise<Result<McpServerConfig, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_get", { serverId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerCreate(params: McpServerCreateParams) : Promise<Result<McpServerConfig, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_create", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerUpdate(serverId: string, patch: McpServerPatch) : Promise<Result<McpServerConfig, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_update", { serverId, patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerDelete(serverId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_delete", { serverId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerTestConnection(serverId: string) : Promise<Result<McpServerStatus, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_test_connection", { serverId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerStatusList() : Promise<Result<McpServerStatus[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_status_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mcpServerToolsList() : Promise<Result<McpToolDescriptor[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mcp_server_tools_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bunRuntimeStatus() : Promise<Result<BunRuntimeStatus, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bun_runtime_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bunRuntimeInstallUserLocal(overwrite: boolean) : Promise<Result<BunRuntimeInstallResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bun_runtime_install_user_local", { overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linkCodexAccount() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_codex_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlinkCodexAccount() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_codex_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async linkClaudeAccount() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("link_claude_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unlinkClaudeAccount() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlink_claude_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rewindTo(sessionId: string, id: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rewind_to", { sessionId, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionStop(sessionId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_stop", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionCreate(params: SessionCreateParams) : Promise<Result<SessionRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_create", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionDelete(sessionId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_delete", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionStart(sessionId: string) : Promise<Result<SessionRecordDto, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_start", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionHistory(sessionId: string) : Promise<Result<MessageRecord[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_history", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteMessage(messageId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_message", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionGet(sessionId: string) : Promise<Result<SessionRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_get", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionList(projectId: string) : Promise<Result<SessionRecord[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_list", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionRename(sessionId: string, newName: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_rename", { sessionId, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionUpdate(sessionId: string, sessionPatch: SessionPatchV2) : Promise<Result<SessionRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_update", { sessionId, sessionPatch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async answerQuestion(sessionId: string, questionId: string, answer: string) : Promise<Result<AskQuestionClaimResult, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("answer_question", { sessionId, questionId, answer }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills() : Promise<Result<SkillItem[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startPlan(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_plan", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completePlan(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_plan", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async continuePlan(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_plan", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelPlan(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_plan", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePlan(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_plan", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assignPlanToSession(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assign_plan_to_session", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unassignPlanFromSession(sessionId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unassign_plan_from_session", { sessionId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTerminalSnapshot(sessionId: string, terminalId: string) : Promise<Result<TerminalSnapshot, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_terminal_snapshot", { sessionId, terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTerminal(sessionId: string, terminalId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_terminal", { sessionId, terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendInterrupt(sessionId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_interrupt", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendPrompt(sessionId: string, prompt: string, imageUrls: string[] | null) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_prompt", { sessionId, prompt, imageUrls }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteQueuedPrompt(request: DeleteQueuedPromptRequest) : Promise<Result<DeleteQueuedPromptOutcome, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_queued_prompt", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProvider(provider: Provider, apiKey: string) : Promise<Result<ProviderRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_provider", { provider, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertProvider(args: UpsertProviderArgs) : Promise<Result<ProviderRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_provider", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEnabledProviders() : Promise<Result<Provider[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_enabled_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviders() : Promise<Result<ProviderDto[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_providers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProvider(providerId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelsCatalog() : Promise<Result<LlmModel[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_models_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProviderFnf(provider: Provider) : Promise<Result<ProviderRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_provider_fnf", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async newProject(name: string, workingDirectories: string[], agentPrimer: string | null) : Promise<Result<ProjectRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("new_project", { name, workingDirectories, agentPrimer }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async editProject(id: string, project: ProjectPatchV2) : Promise<Result<ProjectRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_project", { id, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProject(projectId: string) : Promise<Result<ProjectRecord, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProjects() : Promise<Result<ProjectRecord[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProject(projectId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_project", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planCreate(projectId: string, args: PlanCreateArgs) : Promise<Result<PlanGetPayload, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_create", { projectId, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planList(projectId: string, query: PlanListQuery | null) : Promise<Result<ProjectPlanListPayload, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_list", { projectId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planGet(projectId: string, planId: string) : Promise<Result<PlanGetPayload, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_get", { projectId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planUpdate(projectId: string, args: PlanUpdateArgs) : Promise<Result<PlanGetPayload, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_update", { projectId, args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planCancel(projectId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_cancel", { projectId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async planDelete(projectId: string, planId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan_delete", { projectId, planId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async personalityCreate(name: string, description: string, systemPrompt: string) : Promise<Result<PersonalityModelDto, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("personality_create", { name, description, systemPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async personalityUpdate(id: string, name: string, description: string, systemPrompt: string) : Promise<Result<PersonalityModelDto, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("personality_update", { id, name, description, systemPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async personalityDelete(id: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("personality_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async personalityList() : Promise<Result<PersonalityModelDto[], TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("personality_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewStart(params: PreviewStartParams) : Promise<Result<PreviewSession, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_start", { params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewStop(projectId: string) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_stop", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewReload(projectId: string) : Promise<Result<PreviewSession, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_reload", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewStatus(projectId: string) : Promise<Result<PreviewStatusResponse, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_status", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async slackStartOauth() : Promise<Result<SlackStartOAuthResponse, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("slack_start_oauth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async slackStatus() : Promise<Result<SlackStatus, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("slack_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async slackSetEnabled(enabled: boolean) : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("slack_set_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async slackDisconnect() : Promise<Result<null, TauriError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("slack_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AgentKind = "crew" | "planner" | "executor" | "verifier" | "researcher" | "designer"
export type ApplyPatchArgs = { diff: string; workspace_index: number | null }
export type ApplyPatchPayload = { paths: string[] }
export type ApplySkillPayload = { success: boolean; skill_name: string }
export type AskQuestionAnswerSource = "desktop" | "slack_button" | "slack_modal"
export type AskQuestionArgs = { question: string; details: string; options: string[] }
export type AskQuestionClaimResult = { question_id: string; answer_source: AskQuestionAnswerSource; outcome: AskQuestionClaimStatus }
export type AskQuestionClaimStatus = "accepted" | "rejected_already_answered" | "invalid"
export type AskQuestionPayload = { answer: string }
export type BlprntEventKind = "backendReady" | "reportBugMenuClicked" | "sessionEvent" | "error" | "oauthCallback" | "tunnelMessage" | "mcpServerStatus"
export type BunRuntimeCommandState = "available" | "missing" | "invocation_failed"
export type BunRuntimeCommandStatus = { command: string; detected_version: string | null; state: BunRuntimeCommandState; error: string | null }
export type BunRuntimeInstallResult = { status: BunRuntimeStatus; path_help_snip: string }
export type BunRuntimeStatus = { 
/**
 * `bun` as resolved from PATH.
 */
bun: BunRuntimeCommandStatus; 
/**
 * `bun` at `~/.local/bin/bun` (installed by blprnt). This is informational only.
 */
user_local_bun: BunRuntimeCommandStatus; install_target_path: string }
export type CompactSummary = { id: string; summary: string }
export type ControlEvent = { type: "turnStart" } | { type: "turnStop" } | { type: "compactingStart" } | { type: "compactingDone" }
export type DeleteQueuedPromptOutcome = "Deleted" | "AlreadyStarted" | "NotFound"
export type DeleteQueuedPromptRequest = { session_id: string; queue_item_id: string }
/**
 * Category of error for frontend handling.
 */
export type ErrorCategory = "provider" | "tool" | "engine" | "auth" | "network" | "internal"
/**
 * Structured error event for frontend consumption.
 * Carries category, code, message, and recoverability information.
 */
export type ErrorEvent = { category: ErrorCategory; code: string; message: string; recoverable: boolean }
export type FileReadPayload = { path: string; content: string }
export type FilesReadArgs = { items: FilesReadItem[]; include_line_numbers: boolean | null; workspace_index: number | null }
export type FilesReadErrorPayload = { path: string; error: string }
export type FilesReadItem = { path: string; line_start: bigint | null; line_end: bigint | null }
export type FilesReadPayload = { files: FileReadPayload[]; errors: FilesReadErrorPayload[] }
export type GetPrimerArgs = Record<string, never>
export type GetPrimerPayload = { content: string }
export type GetReferencePayload = { content: string }
export type HistoryMessageSource = "user" | "assistant" | "tool" | "blprnt"
export type HistoryVisibility = "full" | "user" | "assistant" | { partial: PartialVisibility } | "none"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ListSkillsPayload = { items: SkillItem[] }
export type LlmEvent = ({ type: "compactSummary" } & CompactSummary) | ({ type: "reasoningStarted" } & ReasoningStarted) | ({ type: "reasoning" } & ReasoningFinal) | ({ type: "reasoningDelta" } & ReasoningTextDelta) | ({ type: "reasoningDone" } & ReasoningDone) | ({ type: "reasoningEffortChanged" } & ReasoningEffortChanged) | ({ type: "skillApplied" } & SkillApplied) | ({ type: "responseStarted" } & ResponseStarted) | ({ type: "response" } & Response) | ({ type: "responseDelta" } & ResponseDelta) | ({ type: "responseDone" } & ResponseDone) | ({ type: "toolCallStarted" } & ToolCallStarted) | ({ type: "toolCallCompleted" } & ToolCallCompleted) | ({ type: "status" } & Status) | ({ type: "tokenUsage" } & TokenUsage) | ({ type: "webSearch" } & WebSearch)
export type LlmModel = { name: string; slug: string; context_length: number; supports_reasoning: boolean; provider_slug: string | null; enabled: boolean }
export type McpAuthConfig = { type: "none" } | { type: "bearer_token"; token: string } | { type: "api_key"; header: string; key: string } | { type: "basic"; username: string; password: string } | { type: "headers"; headers: Partial<{ [key in string]: string }> }
export type McpServerConfig = { id: string; name: string; enabled: boolean; transport: McpTransportConfig; auth: McpAuthConfig }
export type McpServerCreateParams = { name: string; enabled?: boolean; transport: McpTransportConfig; auth?: McpAuthConfig }
export type McpServerLifecycleState = "configured" | "connecting" | "connected" | "degraded" | "disconnected" | "error"
export type McpServerPatch = { name?: string | null; enabled?: boolean | null; transport?: McpTransportConfig | null; auth?: McpAuthConfig | null }
export type McpServerStatus = { server_id: string; state: McpServerLifecycleState; error?: string | null }
export type McpSseHttpTransportConfig = { url: string; headers?: Partial<{ [key in string]: string }> | null }
export type McpStdioTransportConfig = { command: string; args: string[]; env?: Partial<{ [key in string]: string }> | null; cwd?: string | null }
export type McpToolDescriptor = { server_id: string; name: string; description: string; input_schema: JsonValue }
export type McpToolPayload = { server_id: string; name: string; result: JsonValue }
export type McpTransportConfig = ({ type: "stdio" } & McpStdioTransportConfig) | ({ type: "sse_http" } & McpSseHttpTransportConfig)
export type MemoryCreateRequest = { project_id: string; content: string }
export type MemoryDeleteRequest = { project_id: string; path: string }
export type MemoryListRequest = { project_id: string }
export type MemoryListResult = { root_path: string; nodes: MemoryTreeNode[] }
export type MemoryReadRequest = { project_id: string; path: string }
export type MemoryReadResult = { path: string; content: string }
export type MemorySearchArgs = { query: string; limit: bigint | null }
export type MemorySearchCommandRequest = { project_id: string; query: string; limit: bigint | null }
export type MemorySearchResult = { memories: MemorySearchResultItem[] }
export type MemorySearchResultItem = { title: string; content: string; score: number }
export type MemoryTreeNode = { type: "directory"; name: string; path: string; children: MemoryTreeNode[] } | { type: "file"; name: string; path: string }
export type MemoryUpdateRequest = { project_id: string; path: string; content: string }
export type MemoryWriteArgs = { content: string }
export type MemoryWriteResult = { status: MemoryWriteStatus; path: string; date: string }
export type MemoryWriteStatus = "written"
export type MessageContent = ({ type: "text" } & MessageText) | ({ type: "image64" } & MessageImage64) | ({ type: "thinking" } & MessageThinking) | ({ type: "tool_use" } & MessageToolUse) | ({ type: "tool_result" } & MessageToolResult) | ({ type: "token_usage" } & TokenUsage) | ({ type: "info" } & Signal) | ({ type: "warning" } & Signal) | ({ type: "error" } & Signal) | ({ type: "web_search" } & MessageWebSearch)
export type MessageImage64 = { image_64: string; media_type: string }
export type MessageRecord = { id: string; rel_id: string; turn_id: string; step_id: string; role: MessageRole; content: MessageContent; token_usage?: number | null; visibility: HistoryVisibility; reasoning_effort?: ReasoningEffort | null; memory_dirty?: boolean | null; created_at: number; updated_at: number; session_id: string; parent_id: string | null }
export type MessageRole = "system" | "user" | "assistant"
export type MessageText = { text: string; signature: string | null }
export type MessageThinking = { thinking: string; signature: string; source_provider: Provider | null }
export type MessageToolResult = { tool_use_id: string; content: ToolUseResponse }
export type MessageToolUse = { id: string; tool_id: ToolId; input: JsonValue; subagent_details: SubagentDetails | null; signature: string | null }
export type MessageWebSearch = { url: string; title: string; start_index: bigint; end_index: bigint }
export type PartialVisibility = "error" | "warning" | "tool_result" | "tool_request"
export type PathList = string[]
export type PauseReason = "UserInterrupted"
export type PersonalityModelDto = { id: string; name: string; description: string; system_prompt: string; is_default: boolean; is_user_defined: boolean; created_at: string; updated_at: string }
export type PlanContentPatch = { hunks: PlanContentPatchHunk[] }
export type PlanContentPatchHunk = { before?: string[]; delete?: string[]; insert?: string[]; after?: string[] }
export type PlanCreateArgs = { name: string; description: string; content: string; todos: PlanTodoItem[] | null }
export type PlanCreatePayload = { id: string; name: string; description: string; created_at: string; updated_at: string }
export type PlanDeleteArgs = { id: string }
export type PlanDeletePayload = { id: string }
export type PlanDocumentStatus = "pending" | "in_progress" | "completed" | "archived"
export type PlanGetArgs = { id: string }
export type PlanGetPayload = { id: string; name: string; description: string; content: string; created_at: string; updated_at: string; status?: PlanDocumentStatus; parent_session_id?: string | null; todos: PlanTodoItem[] }
export type PlanListArgs = Record<string, never>
export type PlanListPayload = { items: PlanSummary[] }
export type PlanListQuery = { search?: string | null; sort?: PlanListSort | null; status_filter?: PlanDocumentStatus[] | null }
export type PlanListSort = { by?: PlanListSortBy; direction?: SortDirection }
export type PlanListSortBy = "name" | "created_at" | "updated_at"
export type PlanStatus = "pending" | "in_progress" | "complete" | "unknown"
export type PlanSummary = { id: string; name: string; description: string; created_at: string; updated_at: string }
export type PlanTodoItem = { id: string; content: string; status: PlanStatus }
export type PlanUpdateArgs = { id: string; name: string | null; description: string | null; content: string | null; content_patch: PlanContentPatch | null; todos: PlanTodoItem[] | null; status: PlanDocumentStatus | null }
export type PlanUpdatePayload = { id: string; name: string; description: string; created_at: string; updated_at: string }
export type PreviewDetectedServer = { language: string | null; framework: string | null; suggested_port: number | null; detected_command: string | null }
export type PreviewMode = "dev" | "static"
export type PreviewServerAction = "attached" | "started"
export type PreviewSession = { id: string; project_id: string; mode: PreviewMode; status: PreviewSessionStatus; partition_id: string; url: string; created_at: string }
export type PreviewSessionStatus = "starting" | "ready" | "error" | "stopped"
export type PreviewStartParams = { project_id: string; mode: PreviewMode; dev_server_url: string | null; static_path: string | null; allowed_hosts: string[] | null; instrumentation_enabled?: boolean; proxy_port: number | null; static_port: number | null }
export type PreviewStatusResponse = { status: PreviewSessionStatus; last_error: TauriError | null; server_action: PreviewServerAction | null; detected: PreviewDetectedServer | null; url: string | null; was_auto_started: boolean | null }
export type ProjectPatchV2 = { name?: string | null; working_directories?: PathList | null; agent_primer?: string | null; updated_at?: number }
export type ProjectPlanListItem = { id: string; name: string; description: string; created_at: string; updated_at: string; status?: PlanDocumentStatus; parent_session_id?: string | null }
export type ProjectPlanListPayload = { items: ProjectPlanListItem[] }
export type ProjectRecord = { id: string; name: string; working_directories: PathList; agent_primer?: string | null; created_at: number; updated_at: number }
export type PromptDeleted = { queue_item_id: string }
export type PromptEvent = ({ type: "started" } & PromptStarted) | ({ type: "queued" } & PromptQueued) | ({ type: "deleted" } & PromptDeleted)
export type PromptQueued = { id: string; queue_item_id: string; prompt: string | null }
export type PromptStarted = { id: string; turnId: string; prompt: string; queue_item_id: string | null }
export type Provider = "anthropic" | "openai" | "open_router" | "mock" | "anthropic_fnf" | "openai_fnf" | "blprnt"
export type ProviderDto = ({ id: string; provider: Provider; base_url: string | null; created_at: number; updated_at: number }) & { api_key: string }
export type ProviderRecord = { id: string; provider: Provider; base_url: string | null; created_at: number; updated_at: number }
export type QueueMode = "queue" | "inject"
export type ReasoningDone = { id: string }
export type ReasoningEffort = "none" | "minimal" | "low" | "medium" | "high" | "xhigh"
export type ReasoningEffortChanged = { effort: ReasoningEffort }
export type ReasoningFinal = { id: string; reasoning: string }
export type ReasoningStarted = { id: string; turnId: string; stepId: string }
export type ReasoningTextDelta = { id: string; delta: string }
export type Response = { id: string; content: string }
export type ResponseDelta = { id: string; delta: string }
export type ResponseDone = { id: string }
export type ResponseStarted = { id: string; turnId: string; stepId: string }
export type RgSearchArgs = { pattern: string; path: string | null; flags: string[]; workspace_index: number | null }
export type RgSearchPayload = { stdout: string }
export type RuntimeState = "Idle" | "Running" | { Paused: PauseReason }
export type SessionCreateParams = { project_id: string; personality_key?: string | null; name: string; description: string; agent_kind: AgentKind; yolo: boolean; read_only: boolean; network_access: boolean; model_override: string; web_search_enabled: boolean | null; reasoning_effort: ReasoningEffort; queue_mode: QueueMode }
export type SessionDispatchEvent = ({ eventType: "control" } & ControlEvent) | ({ eventType: "llm" } & LlmEvent) | ({ eventType: "signal" } & SignalEvent) | ({ eventType: "prompt" } & PromptEvent) | ({ eventType: "slack" } & SlackEvent)
export type SessionEvent = { sessionId: string; parentId: string; eventData: SessionDispatchEvent }
export type SessionPatchV2 = { name?: string | null; description?: string | null; agent_kind?: AgentKind | null; yolo?: boolean | null; read_only?: boolean | null; network_access?: boolean | null; personality_key?: string | null; model_id?: string | null; reasoning_effort?: ReasoningEffort | null; queue_mode?: QueueMode | null; token_usage?: number | null; model_override?: string | null; web_search_enabled?: boolean | null; updated_at?: number }
export type SessionPlan = { id: string; status: PlanDocumentStatus }
export type SessionRecord = { id: string; name: string; description?: string | null; agent_kind: AgentKind; yolo: boolean; read_only: boolean; network_access: boolean; reasoning_effort: ReasoningEffort; queue_mode: QueueMode | null; token_usage: number; model_override: string; personality_key?: string | null; web_search_enabled?: boolean | null; plan?: SessionPlan | null; created_at: number; updated_at: number; project: string; parent_id?: string | null }
export type SessionRecordDto = ({ id: string; name: string; description?: string | null; agent_kind: AgentKind; yolo: boolean; read_only: boolean; network_access: boolean; reasoning_effort: ReasoningEffort; queue_mode: QueueMode | null; token_usage: number; model_override: string; personality_key?: string | null; web_search_enabled?: boolean | null; plan?: SessionPlan | null; created_at: number; updated_at: number; project: string; parent_id?: string | null }) & { status: RuntimeState }
export type ShellArgs = { command: string; args: string[]; timeout: bigint | null; workspace_index: number | null }
export type ShellPayload = { stdout: string; stderr: string; exit_code: number }
export type Signal = { id: string | null; message: string; source: HistoryMessageSource | null; error: ErrorEvent | null }
export type SignalEvent = ({ type: "error" } & SignalPayload) | ({ type: "info" } & SignalPayload) | ({ type: "warning" } & SignalPayload)
export type SignalPayload = { id: string | null; message: string; source: HistoryMessageSource; error?: ErrorEvent | null }
export type SkillApplied = { skill: string }
export type SkillItem = { id: string; name: string; description: string; tags?: string[] | null; version?: string | null }
export type SkillScriptPayload = { result: string; error?: string | null }
export type SlackEvent = ({ type: "input" } & SlackInput)
export type SlackInput = { sessionId: string; text: string; slackUserId: string; slackChannelId: string; threadTs: string | null; messageTs: string | null }
export type SlackStartOAuthResponse = { url: string; state: string }
export type SlackStatus = { enabled: boolean; connected: boolean; last_error: string | null }
export type SortDirection = "asc" | "desc"
export type Status = { status: string }
export type SubAgentArgs = { prompt: string; name: string; agent_kind?: AgentKind; model_override: string | null; subagent_id: string | null }
export type SubAgentPayload = { result: string; subagent_id: string | null }
export type SubAgentStatus = "spawned" | "success" | "failure" | "timeout"
export type SubagentDetails = { sessionId: string; parentSessionId: string | null }
export type TauriError = { message: string; error: ErrorEvent | null; trace: string[] | null }
export type TerminalAction = "open" | "write" | "snapshot" | "close"
export type TerminalArgs = { action: TerminalAction; terminal_id: string | null; input: string | null; timeout: bigint | null; workspace_index: number | null }
export type TerminalPayload = { terminal_id: string; 
/**
 * Present for snapshot responses.
 */
snapshot: TerminalSnapshot | null }
export type TerminalSnapshot = { rows: bigint; cols: bigint; lines: string[] }
export type TokenUsage = { inputTokens: number; outputTokens: number }
export type ToolCallCompleted = { id: string; itemId: string; content: ToolUseResponse }
export type ToolCallStarted = { id: string; turnId: string; stepId: string; toolId: ToolId; args: JsonValue; questionId?: string | null; subagentDetails?: SubagentDetails | null }
export type ToolId = "files_read" | "apply_patch" | "shell" | "terminal" | "ask_question" | "plan_create" | "plan_list" | "plan_get" | "plan_update" | "plan_delete" | "primer_get" | "primer_update" | "memory_write" | "memory_search" | "rg" | "subagent" | "web_search" | "list_skills" | "apply_skill" | "get_reference" | "skill_script" | { mcp: string } | { unknown: string }
export type ToolUseResponse = ({ type: "success" } & ToolUseResponseSuccess) | ({ type: "error" } & ToolUseResponseError)
export type ToolUseResponseData = ({ type: "files_read" } & FilesReadPayload) | ({ type: "apply_patch" } & ApplyPatchPayload) | ({ type: "shell" } & ShellPayload) | ({ type: "terminal" } & TerminalPayload) | ({ type: "ask_question" } & AskQuestionPayload) | ({ type: "plan_create" } & PlanCreatePayload) | ({ type: "plan_list" } & PlanListPayload) | ({ type: "plan_get" } & PlanGetPayload) | ({ type: "plan_update" } & PlanUpdatePayload) | ({ type: "plan_delete" } & PlanDeletePayload) | ({ type: "get_primer" } & GetPrimerPayload) | ({ type: "update_primer" } & UpdatePrimerPayload) | ({ type: "memory_write" } & MemoryWriteResult) | ({ type: "memory_search" } & MemorySearchResult) | ({ type: "rg_search" } & RgSearchPayload) | ({ type: "subagent" } & SubAgentPayload) | ({ type: "list_skills" } & ListSkillsPayload) | ({ type: "apply_skill" } & ApplySkillPayload) | ({ type: "get_reference" } & GetReferencePayload) | ({ type: "skill_script" } & SkillScriptPayload) | ({ type: "mcp_tool" } & McpToolPayload) | ({ type: "unknown" } & UnknownToolUseResponsePayload) | { type: "default" }
export type ToolUseResponseError = { success: boolean; tool_id: ToolId; error: string; subagent_id?: string | null; subagent_status?: SubAgentStatus | null }
export type ToolUseResponseSuccess = { success: boolean; data: ToolUseResponseData; message: string | null }
export type TunnelMessage = { type: "slack_oauth_callback" } | { type: "payment_success" } | ({ type: "authentication" } & TunnelMessageAuthentication) | ({ type: "raw" } & TunnelMessageRaw) | { type: "unknown" }
export type TunnelMessageAuthentication = { token: string }
export type TunnelMessageRaw = { raw: string }
export type UnknownToolUseResponsePayload = { original_type?: string | null; raw: JsonValue; error: string }
export type UpdatePrimerArgs = { content: string }
export type UpdatePrimerPayload = { content: string }
export type UpsertProviderArgs = { provider: Provider; api_key: string; base_url: string }
export type WebSearch = { id: string; webSearch: WebSearchData }
export type WebSearchData = { url: string; title: string; startIndex: bigint; endIndex: bigint }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
