/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as RunsRunIdIndexRouteImport } from './routes/runs/$runId/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as IssuesIssueIdIndexRouteImport } from './routes/issues/$issueId/index'
import { Route as EmployeesEmployeeIdIndexRouteImport } from './routes/employees/$employeeId/index'
import { Route as EmployeesEmployeeIdChatRouteImport } from './routes/employees/$employeeId/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdIndexRoute = RunsRunIdIndexRouteImport.update({
  id: '/runs/$runId/',
  path: '/runs/$runId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdIndexRoute = IssuesIssueIdIndexRouteImport.update({
  id: '/issues/$issueId/',
  path: '/issues/$issueId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdIndexRoute =
  EmployeesEmployeeIdIndexRouteImport.update({
    id: '/employees/$employeeId/',
    path: '/employees/$employeeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeesEmployeeIdChatRoute = EmployeesEmployeeIdChatRouteImport.update({
  id: '/employees/$employeeId/chat',
  path: '/employees/$employeeId/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/employees/$employeeId/chat': typeof EmployeesEmployeeIdChatRoute
  '/employees/$employeeId/': typeof EmployeesEmployeeIdIndexRoute
  '/issues/$issueId/': typeof IssuesIssueIdIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/runs': typeof RunsIndexRoute
  '/employees/$employeeId/chat': typeof EmployeesEmployeeIdChatRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdIndexRoute
  '/issues/$issueId': typeof IssuesIssueIdIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/runs/$runId': typeof RunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/employees/$employeeId/chat': typeof EmployeesEmployeeIdChatRoute
  '/employees/$employeeId/': typeof EmployeesEmployeeIdIndexRoute
  '/issues/$issueId/': typeof IssuesIssueIdIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/runs/$runId/': typeof RunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees/'
    | '/issues/'
    | '/onboarding/'
    | '/projects/'
    | '/providers/'
    | '/runs/'
    | '/employees/$employeeId/chat'
    | '/employees/$employeeId/'
    | '/issues/$issueId/'
    | '/projects/$projectId/'
    | '/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/issues'
    | '/onboarding'
    | '/projects'
    | '/providers'
    | '/runs'
    | '/employees/$employeeId/chat'
    | '/employees/$employeeId'
    | '/issues/$issueId'
    | '/projects/$projectId'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/employees/'
    | '/issues/'
    | '/onboarding/'
    | '/projects/'
    | '/providers/'
    | '/runs/'
    | '/employees/$employeeId/chat'
    | '/employees/$employeeId/'
    | '/issues/$issueId/'
    | '/projects/$projectId/'
    | '/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  EmployeesEmployeeIdChatRoute: typeof EmployeesEmployeeIdChatRoute
  EmployeesEmployeeIdIndexRoute: typeof EmployeesEmployeeIdIndexRoute
  IssuesIssueIdIndexRoute: typeof IssuesIssueIdIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  RunsRunIdIndexRoute: typeof RunsRunIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId/': {
      id: '/runs/$runId/'
      path: '/runs/$runId'
      fullPath: '/runs/$runId/'
      preLoaderRoute: typeof RunsRunIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId/': {
      id: '/issues/$issueId/'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId/'
      preLoaderRoute: typeof IssuesIssueIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId/': {
      id: '/employees/$employeeId/'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId/'
      preLoaderRoute: typeof EmployeesEmployeeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId/chat': {
      id: '/employees/$employeeId/chat'
      path: '/employees/$employeeId/chat'
      fullPath: '/employees/$employeeId/chat'
      preLoaderRoute: typeof EmployeesEmployeeIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  EmployeesEmployeeIdChatRoute: EmployeesEmployeeIdChatRoute,
  EmployeesEmployeeIdIndexRoute: EmployeesEmployeeIdIndexRoute,
  IssuesIssueIdIndexRoute: IssuesIssueIdIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  RunsRunIdIndexRoute: RunsRunIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
